"""
Django settings for project_two project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import environ
from pathlib import Path
import os
from datetime import timedelta #for token lifetime settings
import logging #  for logging my signals.py handling of recipe updates,invalidating cache etc

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
env= environ.Env() #you did not call read_env_file here, so it will be called in dev/prod only


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY= env('SECRET_KEY',default=None) #will be set by dev/prod,also add a default to avoid errors

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG =False # will be set by dev/prod

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',#websockket server for handling reviews/comments in real time(async ops)
    'channels',# a lib that extends django to support websockets and async features
    'recipes',
    'users', #handles the custom user logic
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',# for building the API endpoints
    'rest_framework_simplejwt',# for token based auth
    'drf_spectacular',#API schema documentation and swagger ui generation
    'drf_spectacular_sidecar',# for offline swagger ui assets/accessibility
    'django_celery_beat',  # Celery Beat for scheduled tasks
    'django_celery_results',  # Celery result backend support
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',#Users must be loaded first
    'users.middleware.BlockedUserMiddleware',#And get checked if they are blocked
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
'''this keeps all your api specific logic-like permission/auth classes,pagination,openapi schema gen etc
separate rom your general django settings'''
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
         'rest_framework.throttling.UserRateThrottle'], 
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',  # Limit anonymous users to 100 requests per day (identify by IP)
        'user': '1000/day',  # Limit authenticated users to 1000 requests per day (identify by user account)  
        'uploads': '50/day'},  # Limit file upload requests to 50 per day,supposed to  be scoped in views
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticatedOrReadOnly'],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework_simplejwt.authentication.JWTAuthentication',),
}


# Simple JWT settings for token-based authentication
#this for your nativescript mobile app or react native app frontends and your web app
#might use vue.js for frontend webapp,ionic vue+Capacitor for mobile apps
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), #tokens valid for 1 hour,short life for web sec
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),    #refresh tokens valid for 7 days,long for mobile convenience
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),}# for you nativescript frontend/vue ionic + capacitor

SPECTACULAR_SETTINGS = {
    'TITLE': 'My Recipe app API',
    'DESCRIPTION': 'API for managing recipes, ingredients, categories, tags, reviews, and more.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    #this is good for your  frontend devs,it eases readability of your models/endpoints
    #splits large request/response bodies into their own components
     'COMPONENT_SPLIT_REQUEST': True,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'displayOperationId': True,
    #if you want to use the sidecar for swagger ui in offline mode
    'SWAGGER_UI_DIST': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    },
}

ROOT_URLCONF = 'project_two.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_two.wsgi.application'
# handling async ops while using websockets
ASGI_APPLICATION = 'project_two.asgi.application'


# Database
# use a placeholder for the database settings,a safe fallback if not set by dev/prod

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

CACHES = {#INSTANCE (A)AND CONFIGURATION OF REDIS FOR CACHING PURPOSES,SEPARATE FROM CELERY USAGE
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        #using db 1 for caching rate limiting data,separate from other redis usage
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'IGNORE_EXCEPTIONS': True,  # Avoid crashing if Redis is down
        },
        
    }
}

CACHE_TIMEOUT = {
    'recipe_search': 60 * 60,  # Cache search results for 1 hour
    'recipe_detail': 60 * 60 * 2,  # Cache recipe details for 2 hrs
    'random_recipe': 60 * 30,  # Cache random recipe for 30 mins
    'spoonacular': 60 * 60 * 24,  # Cache Spoonacular API responses for 24 hours
}
#configure channels to use redis as the channel layer backend and real-time message broker/real time recipe updates
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],# using default redis db 0 for channels
        },
    },              
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

#the folder on your machine where files(pictures) are stored
MEDIA_ROOT=os.path.join(BASE_DIR,'media')
#The url that browser/app uses to access the file
MEDIA_URL='/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Use a custom user model for the project aka 'the profile constructor' of Users including You(superuser)
AUTH_USER_MODEL = 'users.User'

# ================================================================================
# EXTENSIVE LOGGING CONFIGURATION
# ================================================================================
# Comprehensive logging setup for signals, consumers, and cache operations
# Logs are written to both console and file for debugging and monitoring
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # Keep Django's default loggers intact
    'formatters': {
        # Standard format for most logs
        'verbose': {
            'format': '[{levelname}] {asctime} | {name} | {funcName}:{lineno} | {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        # Detailed format with extra context
        'detailed': {
            'format': '[{levelname}] {asctime} | {name} | {filename}:{funcName}:{lineno} | Process:{process} Thread:{thread} | {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        # Simple format for production
        'simple': {
            'format': '[{levelname}] {asctime} | {name} | {message}',
            'style': '{',
        },
        # JSON-compatible format for structured logging
        'json_format': {
            'format': '{"level": "%(levelname)s", "time": "%(asctime)s", "logger": "%(name)s", "message": "%(message)s"}',
            'style': '%',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        # Console output handler for development
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        # File handler for signals logging
        'signals_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'signals.log'),
            'maxBytes': 5242880,  # 5 MB
            'backupCount': 10,
            'formatter': 'detailed',
        },
        # File handler for consumers (WebSocket) logging
        'consumers_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'consumers.log'),
            'maxBytes': 5242880,  # 5 MB
            'backupCount': 10,
            'formatter': 'detailed',
        },
        # File handler for cache operations
        'cache_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'cache.log'),
            'maxBytes': 5242880,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        # File handler for all application logs
        'app_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'app.log'),
            'maxBytes': 10485760,  # 10 MB
            'backupCount': 20,
            'formatter': 'detailed',
        },
        # File handler for errors only
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'errors.log'),
            'maxBytes': 5242880,  # 5 MB
            'backupCount': 15,
            'formatter': 'detailed',
        },
        # Null handler to suppress propagation when needed
        'null': {
            'class': 'logging.NullHandler',
        },
    },
    'loggers': {
        # Logger for recipes.signals - handles cache invalidation and model signals
        'recipes.signals': {
            'handlers': ['console', 'signals_file', 'cache_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Logger for recipes.consumers - handles WebSocket consumer operations
        'recipes.consumers': {
            'handlers': ['console', 'consumers_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Logger for cache operations
        'recipes.cache': {
            'handlers': ['console', 'cache_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Root logger for the recipes app
        'recipes': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Django logger for framework-level events
        'django': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Django database logger for SQL queries (can be verbose)
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'ERROR',
            'propagate': False,
        },
        # Django request logger
        'django.request': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Default logger for all other modules
        '': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': True,
        },
        # Logger for Spoonacular API integration
        'spoonacular_service': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        # Logger for users signals and tasks
        'users.signals': {
            'handlers': ['console', 'signals_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Logger for Celery tasks
        'users.tasks': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'recipes.tasks': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ================================================================================
# CELERY CONFIGURATION
# ================================================================================
# Configure Celery for asynchronous task execution
# Redis is used as the message broker for task queuing

# Celery broker URL (Redis connection string)
#INSTANCE (B)use a different port t o separate it from your caching redis instance.
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://127.0.0.1:6380')

# Celery result backend URL (where results are stored)
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://127.0.0.1:6380')

# Task serialization settings
CELERY_ACCEPT_CONTENT = ['json']  # Accept JSON from clients
CELERY_TASK_SERIALIZER = 'json'  # Serialize tasks to JSON format
CELERY_RESULT_SERIALIZER = 'json'  # Serialize results to JSON format
CELERY_TIMEZONE = TIME_ZONE  # Use Django's configured timezone

# Task execution settings
CELERY_TASK_TRACK_STARTED = True  # Track when tasks start executing
CELERY_TASK_TIME_LIMIT = 30 * 60  # Hard time limit (30 minutes)
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # Soft time limit (25 minutes)

# Result backend settings
CELERY_RESULT_EXPIRES = 3600  # Results expire after 1 hour
CELERY_RESULT_PERSISTENT = True  # Keep results even after expiry in logs

# Task routing (optional - organize tasks by app)
CELERY_TASK_ROUTES = {
    'users.tasks.*': {'queue': 'email'},  # Route all user tasks to 'email' queue
    'recipes.tasks.*': {'queue': 'maintenance'},  # Route recipe tasks to 'maintenance' queue
}

# Celery Beat Schedule - import from separate config
from project_two.celery_config import CELERY_BEAT_SCHEDULE

# Maximum number of tasks a worker can accept at once
CELERY_WORKER_PREFETCH_MULTIPLIER = 4

# Task execution pool (solo = single process, good for development)
# For production, use 'prefork' (multi-process) or 'gevent' (async)
#CELERY_WORKER_POOL = 'solo'  # Uncomment for development or add to dev settings

# Log settings for Celery
CELERY_WORKER_LOG_FORMAT = '[%(levelname)s %(asctime)s %(name)s] %(message)s'
CELERY_WORKER_TASK_LOG_FORMAT = '[%(levelname)s %(asctime)s %(name)s %(task_name)s[%(task_id)s]] %(message)s'
