"""
Django settings for project_two project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import environ
from pathlib import Path
import os
from datetime import timedelta #for token lifetime settings
import logging #  for logging my signals.py handling of recipe updates,invalidating cache etc

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
env= environ.Env() #you did not call read_env_file here, so it will be called in dev/prod only


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY= env('SECRET_KEY',default=None) #will be set by dev/prod,also add a default to avoid errors

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG =False # will be set by dev/prod

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'recipes',
    'users', #handles the custom user logic
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'drf_spectacular_sidecar',# for offline swagger ui assets/accessibility
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
'''this keeps all your api specific logic-like permission/auth classes,pagination,aopenapi schema gen etc
separate rom your general django settings'''
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
         'rest_framework.throttling.UserRateThrottle'], 
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',  # Limit anonymous users to 100 requests per day (identify by IP)
        'user': '1000/day',  # Limit authenticated users to 1000 requests per day (identify by user account)  
        'uploads': '50/day'},  # Limit file upload requests to 50 per day,supposed to  be scoped in views
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticatedOrReadOnly'],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework_simplejwt.authentication.JWTAuthentication',),
}


# Simple JWT settings for token-based authentication
#this for your nativescript mobile app or react native app frontends and your web app
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), #tokens valid for 1 hour,short life for web sec
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),    #refresh tokens valid for 7 days,long for mobile convenience
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),}# for you nativescript frontend

SPECTACULAR_SETTINGS = {
    'TITLE': 'My Recipe app API',
    'DESCRIPTION': 'API for managing recipes, ingredients, categories, tags, reviews, and more.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    #this is good for your  frontenddevs,it eases readability of your models/endpoints
    #splits large request/response bodies into their own components
     'COMPONENT_SPLIT_REQUEST': True,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'displayOperationId': True,
    #if you want to use the sidecar for swagger ui in offline mode
    'SWAGGER_UI_DIST': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    },
}

ROOT_URLCONF = 'project_two.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_two.wsgi.application'
# handling async ops while using websockets
ASGI_APPLICATION = 'project_two.asgi.application'


# Database
# use a placeholder for the database settings,a safe fallback if not set by dev/prod

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        #using db 1 for caching rate limiting data,separate from other redis usage
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'IGNORE_EXCEPTIONS': True,  # Avoid crashing if Redis is down
        }
    }
}

#configure channels to use redis as the channel layer backend and real-time message broker/real time recipe updates
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],# using default redis db 0 for channels
        },
    },              
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

#the folder on your machine where files(pictures) are stored
MEDIA_ROOT=os.path.join(BASE_DIR,'media')
#The url that browser/app uses to access the file
MEDIA_URL='/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Use a custom user model for the project aka 'the profile constructor' of Users including You(superuser)
AUTH_USER_MODEL = 'users.User'

# ================================================================================
# EXTENSIVE LOGGING CONFIGURATION
# ================================================================================
# Comprehensive logging setup for signals, consumers, and cache operations
# Logs are written to both console and file for debugging and monitoring
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # Keep Django's default loggers intact
    'formatters': {
        # Standard format for most logs
        'verbose': {
            'format': '[{levelname}] {asctime} | {name} | {funcName}:{lineno} | {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        # Detailed format with extra context
        'detailed': {
            'format': '[{levelname}] {asctime} | {name} | {filename}:{funcName}:{lineno} | Process:{process} Thread:{thread} | {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        # Simple format for production
        'simple': {
            'format': '[{levelname}] {asctime} | {name} | {message}',
            'style': '{',
        },
        # JSON-compatible format for structured logging
        'json_format': {
            'format': '{"level": "{levelname}", "time": "{asctime}", "logger": "{name}", "message": "{message}"}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        # Console output handler for development
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        # File handler for signals logging
        'signals_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'signals.log'),
            'maxBytes': 5242880,  # 5 MB
            'backupCount': 10,
            'formatter': 'detailed',
        },
        # File handler for consumers (WebSocket) logging
        'consumers_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'consumers.log'),
            'maxBytes': 5242880,  # 5 MB
            'backupCount': 10,
            'formatter': 'detailed',
        },
        # File handler for cache operations
        'cache_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'cache.log'),
            'maxBytes': 5242880,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        # File handler for all application logs
        'app_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'app.log'),
            'maxBytes': 10485760,  # 10 MB
            'backupCount': 20,
            'formatter': 'detailed',
        },
        # File handler for errors only
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'errors.log'),
            'maxBytes': 5242880,  # 5 MB
            'backupCount': 15,
            'formatter': 'detailed',
        },
        # Null handler to suppress propagation when needed
        'null': {
            'class': 'logging.NullHandler',
        },
    },
    'loggers': {
        # Logger for recipes.signals - handles cache invalidation and model signals
        'recipes.signals': {
            'handlers': ['console', 'signals_file', 'cache_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Logger for recipes.consumers - handles WebSocket consumer operations
        'recipes.consumers': {
            'handlers': ['console', 'consumers_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Logger for cache operations
        'recipes.cache': {
            'handlers': ['console', 'cache_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Root logger for the recipes app
        'recipes': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Django logger for framework-level events
        'django': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Django database logger for SQL queries (can be verbose)
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'ERROR',
            'propagate': False,
        },
        # Django request logger
        'django.request': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Default logger for all other modules
        '': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': True,
        },
    },
}
