# Generated by Django 5.2.5 on 2026-04-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_spoonacularcache_localrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoonacularcache',
            name='access_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spoonacularcache',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='spoonacularcache',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='spoonacularcache',
            name='spoonacular_id',
            field=models.IntegerField(db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='spoonacularcache',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spoonacularcache',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='localrecipe',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
